function Header() {
    return <div className='layout-header'>
       
        <title>Oceeco</title>
        <meta name="Oceeco is a webapp that teaches the impacts of plastics to the ocean and its inhabitants" content="Generated by create next app" />
        <link rel="icon" href="oceecologo.png" />
     

      <div className="navbar">
        <div className="navlogo">
            <img
              className="navlogo" 
              src ="logomarkgradient.png"
            />
        </div>
          <div 
          className="navmenu">
          <img
              className="navmenu" 
              src ="menu.png"
          />
          </div>
      </div>
    </div>
}

export default Header