import {useRouter} from "next/router";
import Head from 'next/head'
import styles from '../styles/Home.module.css'

function Header() {

  const r = useRouter();

    return <div className='layout-header'>
       
       <Head>
        <title>Oceeco</title>
        <meta name="Oceeco is a webapp that teaches the impacts of plastics to the ocean and its inhabitants" content="Generated by create next app" />
        <link rel="icon" href="/logomarkgradient.png" />
	     </Head>
     

      <div className="navbar">
        <div className={styles.navlogo}
        onClick={
          ()=>r.push("/")
        }>
            <img
              className="navlogo" 
              src ="logomarkgradient.png"
            />
        </div>
          <div 
          className="navmenu">
          <img
              className="navmenu" 
              src ="menu.png"
          />
          </div>
      </div>
    </div>
}

export default Header